language: elixir
elixir:
  - 1.2.5
  - 1.3.3
env:
  - AWS_ACCESS_KEY_ID=foo AWS_SECRET_ACCESS_KEY=bar
sudo: false
before_script:
  - gem install fakes3
  - fakes3 --port 8123 --root .fakes3 &
addons:
  hosts:
    - local.dev
